# -*- coding: utf-8 -*-
"""Week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r94Q3YgDLO_pe5qDlJSzbef_rva6VP1R

APOLO Barnabas
#Week1 Day2 Exercise
"""

## Q1 Print the following output using one line of code:
print ('Hello World')

## Q2 Write code that calculates the result of:
result = (99**3) * 8
print(result)

## Q3 What is the output?
#Coment what is your guess, then run the code and compare

# My guess: The output will be HelloHelloHello

print("Hello" * 3)

#Q4 a) Create a variable called computer_brand which value is the brand name of your computer.
computer_brand = "ASUS"
print(computer_brand)

#Q4 b) Using the computer_brand variable, print a sentence that states the following:
"I have a <computer_brand> computer."
computer_brand = "ASUS"
print("I have a <computer_brand> computer")

#Q5 Create a variable called name, and set it’s value to your name.
#Create a variable called age, and set it’s value to your age.
#Create a variable called shoe_size, and set it’s value to your shoe size.
#Create a variable called info and set it’s value to an interesting sentence about yourself.
name = "Apolo"
print(name)
age= "29"
print(age)
shose_size = "40"
print(shose_size)
info = "God is good"
print(info)

#The sentence must contain all the variables created in parts 1, 2, and 3.
#Have your code print the info message.

print(name, age, shose_size, info)

#Q6 Create two variables, a and b.
#Each variable’s value should be a number.
#If a is bigger than b, have your code print "Hello World".

a = 10
b = 5

if a > b:
    print("Hello World")

#Q7 Write code that asks the user for a number and determines whether this number is odd or even.

# Ask the user for a number
num = int(input("Enter a number: "))

# Check if the number is even or odd

if num % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")

#Q8
# Your name
my_name = "Apolo"

# Ask the user for their name
user_name = input("What's your name? ")

# Compare names and print a funny message
if user_name == my_name:
    print("No way! We have the same name! Twin vibes!")
else:
    print(f"Nice to meet you, {user_name}! I guess you're unique")

#Q9
#Write code that will ask the user for their height in centimeters.
#If they are over 145 cm, print a message that states they are tall enough to ride.
#If they are not tall enough, print a message that says they need to grow some more to ride.

# Ask the user for their height in centimeters
height = int(input("Enter your height in cm: "))

# Check if they are tall enough
if height > 145:
    print("You are tall enough to ride! 🎢")
else:
    print("Oops! You need to grow some more to ride. 🌱")